// This file was auto-generated by Fern from our API Definition.

import { ApiA } from "./api/resources/apiA/client/Client.js";
import { ApiB } from "./api/resources/apiB/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace TestOrgApiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TestOrgApiClient {
    protected readonly _options: TestOrgApiClient.Options;
    protected _apiA: ApiA | undefined;
    protected _apiB: ApiB | undefined;

    constructor(_options: TestOrgApiClient.Options = {}) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get apiA(): ApiA {
        return (this._apiA ??= new ApiA(this._options));
    }

    public get apiB(): ApiB {
        return (this._apiB ??= new ApiB(this._options));
    }
}
