// This file was auto-generated by Fern from our API Definition.

export const TestOrgApiEnvironment = {
    Prod: "https://api.example.com",
} as const;

export type TestOrgApiEnvironment = typeof TestOrgApiEnvironment.Prod;
