// This file was auto-generated by Fern from our API Definition.

import type * as TestOrgApi from "./api/index.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";
import * as errors from "./errors/index.js";

export declare namespace TestOrgApiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TestOrgApiClient {
    protected readonly _options: TestOrgApiClient.Options;

    constructor(_options: TestOrgApiClient.Options = {}) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    /**
     * @param {TestOrgApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.getUsers()
     */
    public getUsers(requestOptions?: TestOrgApiClient.RequestOptions): core.HttpResponsePromise<TestOrgApi.User[]> {
        return core.HttpResponsePromise.fromPromise(this.__getUsers(requestOptions));
    }

    private async __getUsers(
        requestOptions?: TestOrgApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<TestOrgApi.User[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TestOrgApiEnvironment.Default,
                "users",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as TestOrgApi.User[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.TestOrgApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TestOrgApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TestOrgApiTimeoutError("Timeout exceeded when calling GET /users.");
            case "unknown":
                throw new errors.TestOrgApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
