// This file was auto-generated by Fern from our API Definition.

export const TestOrgApiEnvironment = {
    Default: "https://api.example.com",
} as const;

export type TestOrgApiEnvironment = typeof TestOrgApiEnvironment.Default;
